### ISSUE TITLE
global: review all warning messages

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#159]
Go through the cookiecutter getting started and review all warning messages.

- Log issues for all found warnings and add them to the sprint board so they can be fixed.

See also inveniosoftware/invenio#3936

Use cookiecutter and install invenio with latest packages. Look in the out put from all the scripts (bootstrap/setup/...) if there's any warnings.

**Comment by diegodelemos** [comment]
Warnings documented in https://github.com/inveniosoftware/invenio-base/issues/138 and https://github.com/inveniosoftware/invenio-assets/issues/100.
