### ISSUE TITLE
Data modelling issues

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#177]
- ``$schema`` attribute is missing
- ``_bucket`` is overwritten (by incoming post, if _bucket is included in the metadata)
- ``_files`` needs to be serialized in metadata

@slint and I have discussed if Record needs some notion of system fields, that are not overwritten: examples: $schema, _buckets, _files, _deposit, _oai, _id, _owners, ...

Also invenio-records-files needs to some how ensure that files are dumped in the record. A lot of this touches on deposit and is a bigger discussion on how to make it simple to use.

IMPORTANT: see references #176

**Comment by kprzerwa** [comment]
the task needs to be analysed and split on smaller chunks
