### ISSUE TITLE
Readthedocs build failed

### ISSUE THREAD

**Issue by blankoworld** [inveniosoftware/cookiecutter-invenio-instance#182]
[Readthedocs don't display the documentation](https://cookiecutter-invenio-instance.readthedocs.io/en/latest/) and tells that [build failed](https://readthedocs.org/projects/cookiecutter-invenio-instance/builds/).

Is that possible to do something?

This is the URL shown on Github project description :wink:

**Comment by slint** [comment]
Probably a mistake when we created the repository... I'm not sure if we intend to have Read the Docs documentation for the cookiecutter... For example, [`cookiecutter-django`](https://cookiecutter-django.readthedocs.io/en/latest/) has a pretty extensive guide on how to run things after generating the project, which looks very similar to what we have in the [main Invenio documentation](https://invenio.readthedocs.io/en/latest/) (which depends on this cookiecutter).

**Comment by blankoworld** [comment]
So I suggest to delete the URL in Github cookiecutter-invenio-instance description. So that we don't click on a dead URL ;)

I'm talking about this:

![cookiecutter-invenio-instance_url](https://user-images.githubusercontent.com/147417/63926242-ca7c1c00-ca4b-11e9-97f2-428c709f12b4.png)

**Comment by lnielsen** [comment]
For sprint developers: This needs to be fixed in [opensource/repositories.yml](https://github.com/inveniosoftware/opensource/blob/master/repositories.yml) for all cookiecutter modules by adding ``url: ''`` under each repository (see license-changer)
