### ISSUE TITLE
Test all the scenarios of cookiecutter

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/cookiecutter-invenio-instance#197]
after the rc released: https://github.com/inveniosoftware/invenio/issues/3971

**Comment by roksys** [comment]
Travis covers:
- PSQL ES7
- PSQL ES6
- MYSQL ES7
- MYSQL ES7 DataModel = None

To test:

- [ ] PSQL ES7 DataModel = None
- [ ] PSQL ES6 DataModel = None
- [ ] MYSQL ES6
- [ ] MYSQL ES6 DataModel = None
- [ ] SQLITE ES6
- [ ] SQLITE ES7
- [ ] SQLITE ES6  DataModel = None
- [ ] SQLITE ES7  DataModel = None





https://travis-ci.org/inveniosoftware/cookiecutter-invenio-instance

**Comment by equadon** [comment]
Full list of combinations:

- [ ] db=postgresql, es=6, datamodel=Custom
- [ ] db=postgresql, es=6, datamodel=None
- [ ] db=postgresql, es=7, datamodel=Custom
- [ ] db=postgresql, es=7, datamodel=None
- [ ] db=mysql, es=6, datamodel=Custom
- [ ] db=mysql, es=6, datamodel=None
- [ ] db=mysql, es=7, datamodel=Custom
- [ ] db=mysql, es=7, datamodel=None
- [ ] db=sqlite, es=6, datamodel=Custom
- [ ] db=sqlite, es=6, datamodel=None
- [ ] db=sqlite, es=7, datamodel=Custom
- [ ] db=sqlite, es=7, datamodel=None
