### ISSUE TITLE
Cookiecutter vs Invenio version management

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#21]
Define a strategy for how this repository should evolve with new Invenio versions.

Assume e.g. Invenio v3.0.0, 3.0.1, 3.1.0; 3.0.1 is fully compatible with 3.0.0, however, 3.1.0 is not guaranteed to be fully compatible with 3.0.x.

``setup.py`` requires ``invenio[...]~=3.0.0`` - this will take care of installing 3.0.0 or 3.0.1 (once out). Once v3.1.0 is out, we need to update the requirement to ``invenio[...]~=3.1.0``, but we should still support cookiecutter for Invenio v3.0.0 (not indefinitely but for a defined amount of time).

This also relates to how people use this cookiecutter template. 

E.g. we could create a branch for each minor (i.e. 3.0 -> 3.1) release of Invenio, and ask users to cookiecut that branch. I.e. something like (not sure if below is possible):

```console
$ cookiecutter https://github.com/inveniosoftware/cookiecutter-invenio-instance@maint-3.0
```

Last but not least, we may benefit from writing into the repository the commit hash or similar of the cookiecutter template used to generate a project (to later allow for diffing etc).

**Comment by slint** [comment]
FYI, checking out a specific tag [is possible](https://cookiecutter.readthedocs.io/en/latest/advanced/cli_options.html#command-line-options) and looks something like `cookiecutter https://github.com/inveniosoftware/cookiecutter-invenio-instance.git --checkout 3.0.1`

**Comment by lnielsen** [comment]
👍 I can see it works for both tags, branches and commits..... I thinking a branch might be the best, since then we can easily make updates to the templates without having to update documentation

**Comment by dinosk** [comment]
https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/48 mentions the branch choice in the README.rst, and after thinking for a way to embed the template hash in the generated instance,
I thought of using a git hook to do the job.
At first I tried to render the hash from a jinja template, but cookiecutter doesn't provide any information about the template used, and operates from the generated instance dir.
I can think of either using the git hook which is included in the PR, or another possibility would be to add the info manually. The hook though is outside the git repo, and cannot be committed, so we would have to either add it manually or by running a script. Any suggestions are welcome.

**Comment by lnielsen** [comment]
@tiborsimko You have ideas?
