### ISSUE TITLE
tests: unused block of code

### ISSUE THREAD

**Issue by KonstantinaStoikou** [inveniosoftware/cookiecutter-invenio-instance#212]
In [test_api_record_files.py](https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/tests/api/test_api_record_files.py#L10) there is a syntax error in unused block of code: 
``` python
def _new_record_payload():
    """Return the payload to create a new record."""
    data = {
            "title": "The title of the record ",
            "contributors": [
                {"name": "Ellis Jonathan"},
            ]
        }
    return headers, data
```

**Comment by ppanero** [comment]
Blocked by https://github.com/inveniosoftware/invenio-jsonschemas/issues/89
