### ISSUE TITLE
tests: upgrade v3.3 to v3.4 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#225]
With the new SemanticUI, we should ensure that:

1) Cookiecut a new v3.3 instance:

```
$ cookiecutter gh:inveniosoftware/cookiecutter-invenio-instance -c v3.3
$ cd my-site
$ docker-compose up -d
$ ./scripts/bootstrap
$ ./scripts/setup
$ ./scripts/server
```

2)  Upgrade it to Invenio v3.4 (alpha):

Exact steps to be defined, but would include:
- Change Pipfile, and Piplock
- Rebuild (bootstrap)
- Run and everything should work as before

3) Change to SemanticUI:

- Add ``APP_THEME = ['semantic-ui']`` to config.
- Rebuild (bootstrap)
- Run and we should have everything in bootstrap

**Comment by mvidalgarcia** [comment]
### User wants to keep bootstrap3:

- Replace invenio version in `Pipfile`
```Pipfile
invenio = { version = ">=3.4.0a1,<3.5.0",...
```
- Remove lock file and generate it again:

```console
$ rm Pipfile.lock
$ pipenv lock --dev --pre
```

- Move `site-packages/invenio_<theme|i18n|previewer>/assets` to `bootstrap3` folder. (I guess this should be changed somehow as it's messy, related: https://github.com/inveniosoftware/invenio-assets/issues/124)
- Run `./scripts/bootstrap`
- Add `APP_THEME = ['bootstrap3']` to `config.py`
- Works!

### User wants to upgrade to Semantic-UI:

- Update to `APP_THEME = ['semantic-ui']`.
- Run `./scripts/bootstrap` - Doesn't work

I assume somehow we need to add the [diff between cookiecutter v3.3 and v3.4](https://github.com/inveniosoftware/cookiecutter-invenio-instance/compare/inveniosoftware:v3.3...jrcastro2:semantic-theming), but seems like a lot of changes to do manually. Any ideas?

**Comment by lnielsen** [comment]
Problem also https://github.com/inveniosoftware/invenio-assets/issues/124
