### ISSUE TITLE
v3.4: revert `bootstrap` script before final release

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/cookiecutter-invenio-instance#233]
The v3.4 release currently depends on some Invenio modules that have been released as `pre-releases` (alpha, a1).
Pipenv is not very happy about that and there is no easy way to install such packages pre-releases only.
The `/scripts/bootstrap` has been changed to use `pip` instead.

Check the comments in the script and revert the changes.

**Comment by lnielsen** [comment]
These are the lines:

```
# START: PUT ME BACK
if [ ! -f $pipfile_lock_path ]; then
    echo "'Pipfile.lock' not found. Generating via 'pipenv lock --dev'..."
    pipenv lock --dev --pre
fi

# Installs all packages specified in Pipfile.lock
pipenv sync --dev
# /END: PUT ME BACK

# START: REMOVE ME
# pipenv run pip install -e git+https://github.com/inveniosoftware/invenio.git#egg=invenio["base","auth","metadata","files","postgresql","elasticsearch7"]
# /END: REMOVE ME
```

The changes have already been put back. What's missing is removing the commented code and markers.

**Comment by ppanero** [comment]
Should not be closed, the `--pre` should be removed, not just the comment??
