### ISSUE TITLE
incorrect <div> nesting in frontpage.html 

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/cookiecutter-invenio-instance#247]
Package version (if known): confirmed in current HEAD.

## Describe the bug
The div tags in {{cookiecutter.package_name}}/frontpage.html are not correctly nested - div.container-marketing is never closed.

This causes the page footer to be inconsistently positioned in the front page - it is indented by its inclusion in the dangling div.container-marketing. This also causes the front-page HTML to fail validation (may affect SEO/accesibility?). 

## Steps to Reproduce
1. Bootstrap a new instance
2. View / validate HTML front page - note footer position / no closing tag for div.container-marketing

## Expected behavior

Correctly nested div elements on front page - footer should not be a child of container-marketing. Footer should align consistently with other pages. 

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/7934352/95883126-7678e780-0d72-11eb-8efd-4f9f49bc87b0.png)

## Additional context

**Comment by dfdan** [comment]
(happy to make the (1-line) PR to fix this, but not sure if its relevent if this is replaced by semantic-ui?)

**Comment by ppanero** [comment]
@zzacharo will this be touched by the UI works you and @Glignos are doing? Otherwise, I think we would happily accept the contribution @dfdan :) Thanks for reporting!

**Comment by zzacharo** [comment]
@ppanero not sure, probably not :)

**Comment by ppanero** [comment]
Then I'd say it's a go @dfdan :)

**Comment by fenekku** [comment]
pending invenio-previewer
