### ISSUE TITLE
Travis: Test the .travis.yml for a new project

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#25]
Use cookiecutter to generate a new template, push to github, enable travis and see that the generated .travis.yml works.

**Comment by slint** [comment]
The current issue appears to be that `requirements-builder` fails to parse the `invenio[...]~=1.0.0` specifier in `setup.py`. There's https://github.com/inveniosoftware/requirements-builder/pull/36 which adds support for it, so it might be worth looking into addressing this issue by trying out the new `requirements-builder`
