### ISSUE TITLE
search: search results items are not shown

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#250]
## Describe the bug

The search page is not rendering results (probably due to a missing template or similar).

## Steps to Reproduce

Follow the quick start

## Screenshots (if applicable)

Note, that the number of results shows 1, but there's no data show:

![Screenshot 2020-11-30 at 00 29 24](https://user-images.githubusercontent.com/1698163/100556527-45616180-32a3-11eb-908a-9ac1e8e634a2.png)

**Comment by ppanero** [comment]
Oops I duplicated it in https://github.com/inveniosoftware/invenio-search-ui/issues/110 my bad. Closing that one.
