### ISSUE TITLE
pydocstyle, isort, pytest-invenio and requirements issues

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/cookiecutter-invenio-instance#3]
After setting up instance two things from run-tests.sh are failing that are fixable in the template

- pydocstyle:
```
foobar/version.py:1 at module level:
        D205: 1 blank line required between summary line and description (found 0)
tests/api/conftest.py:14 in public function `create_app`:
        D103: Missing docstring in public function
tests/ui/conftest.py:14 in public function `create_app`:
        D103: Missing docstring in public function
tests/e2e/conftest.py:14 in public function `create_app`:
        D103: Missing docstring in public function
```

- isort:
```
--- /home/krnowak/src/foobar/tests/conftest.py:before	2018-03-23 10:47:26.316118
+++ /home/krnowak/src/foobar/tests/conftest.py:after	2018-03-23 10:57:06.865053
@@ -6,4 +6,3 @@
 """Common pytest fixtures and plugins."""
 
 from __future__ import absolute_import, print_function
-
```

Other's also fail, but they don't make sense for fresh insance (.e.g manifest check or tests)

**Comment by krzysztof** [comment]
Seems like it's installing ES 6 in version ``6.0.0`` for lowest/release/devel dependencies, is this something user is supposed to fix?
```
env:
  - REQUIREMENTS=lowest E2E="no" ES_VERSION=6.0.0
  - REQUIREMENTS=release DEPLOY=true E2E="yes" E2E_OUTPUT="base64" ES_VERSION=6.0.0
  - REQUIREMENTS=devel E2E="yes" E2E_OUTPUT="base64" ES_VERSION=6.0.0
```

**Comment by krzysztof** [comment]
This line specifies ``elasticsearch2``, should probably be a template variable: https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/.travis.yml#L56

Similarly ES_VERSION is 6.0.0, should also be a variable and made compatible with pip dependency

**Comment by krzysztof** [comment]
This should no longer depend on alpha version of pytest-invenio (once it's released) https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/setup.py#L22

**Comment by krzysztof** [comment]
There's no way for the template renderer to enter this "else" (sqlite):
https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/53990b89311df1b4418f68299b2dd2d066ac6a34/%7B%7Bcookiecutter.project_shortname%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/config.py#L98-L104

Because the wizard asks for either of the first two. Should it be removed?

**Comment by lnielsen** [comment]
Regarding Travis: We should change lowest/release/devel with something like prod requirements (frozen set of requirements that must work) and qa (latest released package versions).

**Comment by slint** [comment]
Clsoed via #18 #17 and others
