### ISSUE TITLE
Clean redis cache for all databases

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#34]
``/scripts/setup`` currently does [not clean redis](https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/scripts/setup#L7).

Not sure how to best clean redis since we have several different modules using redis:
- accounts (sessions)
- cache (cache)
- celery (result backend)
- rest (ratelimiting)

Also, the queue should be purged:

```
invenio index queue init
invenio index queue purge # <- add
```

**Comment by ChiaraBi** [comment]
`redis-py` has the `flushall()` method (https://github.com/andymccurdy/redis-py/blob/71b69ed31a615305c0af18c34a764eee410586bf/redis/client.py#L742) which deletes all the keys from all databases
