### ISSUE TITLE
python 3.6 support

### ISSUE THREAD

**Issue by slint** [inveniosoftware/cookiecutter-invenio-instance#37]
When you run the bootstrap script with python 3.6 you get

```
...
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/lnielsen/envs/my-site/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
...\
```

The problem have been reported before, but not solved as far as I know. Any chance we could get it fixed, so that instructions works for Python 3.6 as well as 3.5

*(copied from https://github.com/inveniosoftware/cookiecutter-invenio-datamodel/issues/10)*

**Comment by slint** [comment]
In addition to this, should we make `python_version` a choice in the cookiecutter?

**Comment by lnielsen** [comment]
I wouldn't make it a choice....just use the latest...

**Comment by lnielsen** [comment]
Seems like the bug can be fixed simply by using a newer release of node-sass version instead of pinning it to 3.8.0

**Comment by dinosk** [comment]
For some reason I cannot reproduce this. I created a new virtualenv w/ python 3.6.0, and ran:
```
$ cookiecutter cookiecutter-invenio-instance
// used all defaults
$ cd my-site
$ ./scripts/bootstrap
// output in attached long_output.txt
```
[long_output.txt](https://github.com/inveniosoftware/cookiecutter-invenio-instance/files/2009366/long_output.txt)

and it worked. Removed the pin from node-sass and tried again, and it worked again. Maybe I'm running the bootstrap script wrong?

**Comment by lnielsen** [comment]
It's because it's finding python2:

```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /Users/dinossimpson/.pyenv/shims/python2
```

**Comment by dinosk** [comment]
Ah right! It had both python3 and 2 and even if python points to 3.6 it will check for python2 first, okie I'll try again.
