### ISSUE TITLE
travis: use docker-compose to spawn services on travis

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/cookiecutter-invenio-instance#45]
Stemmed from https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/43#discussion_r188867258.

**Comment by egabancho** [comment]
@diegodelemos If you don't mind I'll take this for a spin ☺️

**Comment by diegodelemos** [comment]
👍 there is https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/51 PR which might be helpful!
