### ISSUE TITLE
global: enable flask-debugtoolbar

### ISSUE THREAD

**Issue by slint** [inveniosoftware/cookiecutter-invenio-instance#60]
For the `Flask-Debugtoolbar` extension to work, it must also be [added the `invenio_base.apps` entrypoints](https://github.com/zenodo/zenodo/blob/467f7c7fa52f310c04510e4d5356f56edfff9773/setup.py#L208)

Another problem though is that CSP headers are not playing well with the extension: https://github.com/mgood/flask-debugtoolbar/issues/88

**Comment by dinosk** [comment]
The issue was opened in 2015 so I don't think it'll be fixed with the suggestion mentioned there. We could turn off CSP for debug mode?
