### ISSUE TITLE
datamodel: fix persistent identifier serialisation

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#97]
The [quickstart guide](https://invenio.readthedocs.io/en/docs-v3.1/quickstart/crud-operations.html) show the PID in the JSON. However, when I try to run the quickstart guide the ID is not in the output. This impacts 

- REST API 
- UI (when you search for records and try to access an individual record the link goes nowhere)
- Test coverage of cookiecutter is 99%, and the 2 missing lines is related to the serialization  of the pid.

**Comment by ppanero** [comment]
Tested with cookiecutter master and installing https://github.com/inveniosoftware/invenio-records-rest/pull/234 fixes the issue.
