### ISSUE TITLE
webpack: bundles cause webpack size warnings 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#99]
When you run the bootstrap script you get warnings about very big (2.2MB) bundles

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  adminlte (2.24 MiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.cb86bc6cb135e38cbe31.css
      js/1.f8179b682b4f1957cc56.js
      js/2.354a92ac4634091f738b.js
  base (2.24 MiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.cb86bc6cb135e38cbe31.css
      js/1.f8179b682b4f1957cc56.js
      js/3.cb9fb27fbfa249f933bd.js
  i18n_app (2.24 MiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.cb86bc6cb135e38cbe31.css
      js/1.f8179b682b4f1957cc56.js
      js/4.5e976e0d6bbd39f439e4.js
  search_ui_app (2.24 MiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.cb86bc6cb135e38cbe31.css
      js/1.f8179b682b4f1957cc56.js
      js/5.abc761eadb0ee2b8bdaa.js
  search_ui_theme (2.24 MiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.cb86bc6cb135e38cbe31.css
      js/1.f8179b682b4f1957cc56.js
      css/search_ui_theme.d63a24f731803c9f2d46.css
      js/6.23be2997be0d9fd0c6ca.js
  theme-admin (2.24 MiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.cb86bc6cb135e38cbe31.css
      js/1.f8179b682b4f1957cc56.js
      css/theme-admin.35fbd8638b957bb7bd67.css
      js/8.526bbb47d1c08bcdb882.js
```

**Comment by kprzerwa** [comment]
After latest merges:
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  img/fontawesome-webfont.76a4f23.svg (348 KiB)
  js/1.a452148e889307a97be6.js (833 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  adminlte (839 KiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.ba0e6041c836b7356017.css
      js/1.a452148e889307a97be6.js
      js/2.f36cf3a52d5721a5bc08.js
  base (837 KiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.ba0e6041c836b7356017.css
      js/1.a452148e889307a97be6.js
      js/3.b4fd6b33bcb9afa66297.js
  i18n_app (837 KiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.ba0e6041c836b7356017.css
      js/1.a452148e889307a97be6.js
      js/4.12f0789ef768e337658c.js
  search_ui_app (837 KiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.ba0e6041c836b7356017.css
      js/1.a452148e889307a97be6.js
      js/5.d607817e63f81284665d.js
  search_ui_theme (837 KiB)
      js/manifest.971ef611d8fa360ea500.js
      css/vendor.ba0e6041c836b7356017.css
      js/1.a452148e889307a97be6.js
      css/search_ui_theme.25db8a1dcb80ffa234a7.css
      js/6.a6c1cede0c6d68320fc2.js
